### ISSUE TITLE
Cannot run example from documentation without getting EOF error

### ISSUE THREAD

**Issue by ryanwalls** [sclasen/swfsm#111]
Running example from here: https://godoc.org/github.com/sclasen/swfsm/fsm#example-FSM

When a workflow execution is kicked off from the Amazon console UI, we get the following error:

```
2016/01/20 14:09:08 component=FSM name=example-fsm-decider action=tick workflow=SupportOptimizationWorkflow workflow-id=128 at=error=deserialize-state-failed err=&s%!(EXTRA *errors.errorString=EOF)
2016/01/20 14:09:08 component=FSM name=example-fsm-decider workflow=SupportOptimizationWorkflow workflow-id=128 run-id=23diUgxev2ot9Juqb7LmbLuDoFKWC7OKF5EW73Ik0dUro= action=tick at=tick-error status=abandoning-task error="EOF"
```

When we kick off the workflow execution programmatically, for some reason the poller never picks it up.

**Comment by ryanwalls** [comment]
FYI, the polling problem when running execution programmatically was the bug related to long polling mentioned here https://github.com/sclasen/swfsm/blob/master/poller/doc.go

**Comment by sclasen** [comment]
Right on thank you! Good catch.
