### ISSUE TITLE
Give access to allowPanics option on FSM or add other configurable way to print stack traces

### ISSUE THREAD

**Issue by ryanwalls** [sclasen/swfsm#133]
During development, it would be really handy to be able to allow panics on FSM's so that we could get nice full stack traces.  

Another option would be to change the `DefaultDecisionErrorHandler` implementation to print a stack trace.  

Thoughts?

**Comment by sclasen** [comment]
was just thinking today to just make `allowPanics` into`AllowPanics`.  Its already that way for activity worker.   Will do shortly.

**Comment by ryanwalls** [comment]
:+1:

**Comment by sclasen** [comment]
closed by #134
