### ISSUE TITLE
Log panic location

### ISSUE THREAD

**Issue by lstoll** [sclasen/swfsm#135]
Currently the panic handlers just print the error message, and this makes it hard to track down where the error is actually coming from. I was thinking about dropping something like this http://play.golang.org/p/jxtnL79k_Z in, and adding a location=<file>:<line> to the log line.

How would you feel about that? If it's an acceptable idea, I'll PR something up.

**Comment by sclasen** [comment]
Looks great :+1:

**Comment by ryanwalls** [comment]
:+1: This will be handy.  I like it.

**Comment by ryanwalls** [comment]
@lstoll Any updates on this?  Would love to have it.

**Comment by lstoll** [comment]
@ryanwalls sorry about the holdups, I've been trying to make sure the reflection is totally safe and doesn't break in weird ways. This has also made me think that it might be nice to have a way to set up a handler for these too, so I'm currently exploring using logrus in here.

**Comment by ryanwalls** [comment]
@lstoll No worries.  I really like https://github.com/inconshreveable/log15.  It gives you line numbers and even call stack if you want it.
