### ISSUE TITLE
Idea:  Add "input" field to ActivityInfo

### ISSUE THREAD

**Issue by ryanwalls** [sclasen/swfsm#143]
Thoughts on adding an "Input" field to ActivityInfo?  I want to reschedule activities that fail, but I want to reschedule them with their original input.  Would be nice if the correlator tracked that input for me.

**Comment by sclasen** [comment]
coming soon to https://github.com/sclasen/swfsm/pull/131

**Comment by sclasen** [comment]
Closed via #131
