### ISSUE TITLE
fail() method in ActivityWork should trim reason to 256 chars before sending to SWF

### ISSUE THREAD

**Issue by ryanwalls** [sclasen/swfsm#161]
Currently the code sends back `err.Error()` as the reason without trimming.  

```
_, failErr := h.SWF.RespondActivityTaskFailed(&swf.RespondActivityTaskFailedInput{
		TaskToken: task.TaskToken,
		Reason:    S(err.Error()),
		Details:   S(err.Error()),
	})
```

If `err.Error()` results in a string longer than 256 characters, SWF fails because the `Reason` field is only allowed 256 chars.

This results in the activity failing, but never successfully sending the failure message back to SWF.

I can send a PR to fix this if you agree with trimming the `Reason` field to 256 characters before responding.  (I don't know how many characters `Details` is allowed, but we should do the same pattern.)

**Comment by sclasen** [comment]
Great catch! Pr?

**Comment by ryanwalls** [comment]
Yep, I'll send a PR.
