### ISSUE TITLE
No option to recover if decider response to SWF fails 

### ISSUE THREAD

**Issue by ryanwalls** [sclasen/swfsm#167]
Currently, in `handleDecisionTask` if the decider response to SWF fails for some reason, we just log the message and return.  

```
if _, err := f.SWF.RespondDecisionTaskCompleted(complete); err != nil {
	f.log("workflow=%s workflow-id=%s run-id=%q action=tick at=decide-request-failed error=%q", s.LS(decisionTask.WorkflowType.Name), s.LS(decisionTask.WorkflowExecution.WorkflowId), s.LS(decisionTask.WorkflowExecution.RunId), err.Error())
	return
}
```

I would like to come up with a mechanism to provide a configurable handler for this type of error similar to how `DecisionErrorHandler` handles errors in `Tick`.  

Thoughts?

If you agree with the approach, I can work on a PR.

**Comment by ryanwalls** [comment]
As a side note on why we need this... we are hitting the 32k character limit frequently when the decider tries to record a marker for the correlator because of how many activities/timers we have outstanding along with their input.  

If you have other ideas for how to reduce our character footprint, happy to get feedback.

**Comment by sclasen** [comment]
Yes, configure your fsms to use s3serializers instead of json.   They write
to swf if under 32k and s3 when over!

Lmk if it's unclear how to use

**Comment by ryanwalls** [comment]
@sclasen My FSM fails on record marker decisions.  Do I need to set both the `Serializer` and `SystemSerializer` to be the s3 serializer?

**Comment by sclasen** [comment]
Definitely the system serializer, but doing both generally doesnt hurt,
since if you are under 32K you just get the behavior of the underlying
serializer which would be json.

**Comment by ryanwalls** [comment]
@sclasen Sweet.  Got it working!

Even with this change, still might be nice to be able to customize what happens when a decider unsuccessfully sends a response to SWF.  (In our case we might want to fail the workflow.)  So thoughts on me adding another type of Handler that could be registered on the FSM?

**Comment by sclasen** [comment]
Yep agree sounds reasonable.
