### ISSUE TITLE
Possible bug:  signaled events behave differently from other events in correlator

### ISSUE THREAD

**Issue by ryanwalls** [sclasen/swfsm#174]
In `EventCorrelator.getId`, in all cases but two the id that is returned is an event id.  In the case of an `ActivityStartedSignal` or `ActivityUpdatedSignal`, `getId` returns the activity id instead.  Is this expected?  

 ```
         case swf.EventTypeWorkflowExecutionSignaled:
		event := h.WorkflowExecutionSignaledEventAttributes
		if event != nil && event.SignalName != nil && event.Input != nil {
			switch *event.SignalName {
			case ActivityStartedSignal, ActivityUpdatedSignal:
				state := new(SerializedActivityState)
				a.Serializer.Deserialize(*event.Input, state)
				id = state.ActivityId
			default:
				id = a.key(event.ExternalInitiatedEventId)
			}
		}
	}
```

I'm using the coordinated activity handler, which is sending signals to the workflow that look like this:

```
{"ActivityId":"2623ce2e-30a7-4b0a-a6ca-06de5246aac9","Input":"{\"PercentComplete\":80}\n"}
```

I was hoping to get the associated activity from the correlator, by calling something like `fsmContext.ActivityInfo(h)` where `h` is my signaled event.  

But since the correlator keys activities by event id instead of a activity id, `fsmContext.ActivityInfo(h)` returns nil.

**Comment by sclasen** [comment]
@ryanwalls is the signal name being sent back for that the `ActivityUpdatedSignal` ? Assuming so but just making sure

**Comment by sclasen** [comment]
Ohh, hmm after looking it seems like you are correct. Let me see if I can figure out the fix.

**Comment by ryanwalls** [comment]
@sclasen Yeah, what we did was just iterate through the ActivityInfos in the correlator and see if the activity id matched the signal activity id.  Then you could return the key, perhaps?

**Comment by sclasen** [comment]
are you watching me code :P , change incoming

**Comment by ryanwalls** [comment]
Haha.  Yep. ;)
