### ISSUE TITLE
DefaultCanceledState can lead to multiple cancellations being sent to SWF

### ISSUE THREAD

**Issue by ryanwalls** [sclasen/swfsm#184]
![image](https://cloud.githubusercontent.com/assets/842653/18070902/5b524efe-6e0e-11e6-88ea-30de994ab26c.png)

Take this set of events.  Basically, a cancellation was requested while a decision task (event 36) was being processed.  The decision task in progress resulted in a schedule activity task decision (event 42).  

When the decision task for the cancellation request is started (event 44), the first event we process is 37.  In our decider we are using the `fsm.CancelWorkflow` method, which transitions to the default cancelled state and adds a decision to cancel the workflow.

The problem is that in the `DefaultCanceledState` if we see other events during the same decision task processing, it adds more cancel workflow decisions.  e.g.  When the fsm processes events 42 and 43, it adds two more decisions to cancel the workflow.  So when all the outcomes are merged, we end up with 3 decisions to cancel the workflow.  The problem is that now SWF errors out with a 400 error that says `ValidationException: Close must be last decision in list`.  

Currently, in our error handler we fail the workflow when we see an error from SWF... 

So... dreaming up ways to solve this problem, and debating if we perhaps should change the implementation of the `DefaultCanceledState`.  Thoughts?  

Options to I'm mulling over:

- Squash workflow cancellations and failures into one decision when we merge outcomes in `Tick` function...  but this seems like a side-effect.  
- Stop processing events in `Tick` when we get to a "terminal" decision, i.e. if we hit a cancel or fail workflow outcome, stop processing events and return.
- There is a `Cancellations` field in the correlator... is this used to track outstanding cancellation decisions?  If so, we could check that in the `DefaultCanceledState` before adding extra cancellation decisions.
- No change to swfsm, instead track cancellations in our state data and implement our own canceled state that checks the state data field.  (But it seems like other people will need this solution, so would prefer a framework solution.)

**Comment by sclasen** [comment]
aha, yes @ryanwalls  you have stumbled on to one of the edges where the per event processing is not the best abstraction.

The interceptor stuff in fsm package can be used to work around this. On all our fsms, we have an afterDecsision interceptor that looks much like

```
func DecisionInterceptor() fsm.DecisionInterceptor {
	return &fsm.FuncInterceptor{
		AfterDecisionFn: func(decision *swf.PollForDecisionTaskOutput, ctx *fsm.FSMContext, outcome *swfsm.Outcome) {
			outcome.Decisions = dedupeCompletes(outcome.Decisions)
		},
	}
}


func dedupeCompletes(in []*swf.Decision) []*swf.Decision {
	//make sure that if there is a complete decision, there is only 1 and its last.
	out := []*swf.Decision{}
	var completeDecision *swf.Decision

	for i, d := range in {
		if *d.DecisionType == swf.DecisionTypeCompleteWorkflowExecution {
			//always take the last one
			// cant use &d cause that gets mutated
			completeDecision = in[i]
		} else {
			out = append(out, d)
		}
	}

	if completeDecision != nil {
		out = append(out, completeDecision)
	}

	return out
}
```


The same concept would apply to any terminating decision, which I think the only ones are  CompleteWorkflow and FailWorkflow.

Should probably get added to swfsm somehow as composable interceptor bits.

**Comment by ryanwalls** [comment]
@sclasen Makes sense.  Will work on a PR later this week.  

This would be a breaking change... but thoughts on creating a `DefaultInterceptor` in a similar vein to things like the `DefaultDecisionErrorHandler` and `DefaultTaskErrorHandler`, that would get initialized on `Init()` to an interceptor that removed start/stop dupes and complete dupes?

**Comment by sclasen** [comment]
Seems pretty legit, I think we have ours applied everywhere anyhow already.

**Comment by amerine** [comment]
Any reason we shouldn't try to extract ours down into here?

**Comment by sclasen** [comment]
Nope, we can/should and make it handle completes and fails.

Though that brings up the question of what to do if there happen to be both
a complete workflow and a fail workflow in the same decision task.

favor completes and drop the fails I guess?

**Comment by sclasen** [comment]
@amerine btw I pasted ours into a comment above

**Comment by ryanwalls** [comment]
I'm also thinking cancel, complete, and fail should be handled in the deduping of close events.  All 3 are treated like close events in SWF I believe.  My preference of priority if all 3 were in the same list of decisions would be "fail" > "complete" > "cancel".  

In our scenarios, if something caused a "fail" decision, then the workflow is not recoverable and should not be marked "complete".  But if a "complete" or "fail" has happened, I think "cancel" can be safely ignored.

**Comment by sclasen** [comment]
ah yep, forgot about cancel.  Sounds reasonable to me, users can always write their own.

If it doesnt make the impl too complex, you could write each of DedupeFail, DedupeComplete, DedupeCancel, and SelectClosingDecision(Fail|Complete|Cancel) behaviors as standalone interceptors, and just compose them together as the DefaultInterceptor, as the interceptors are composable, just like deciders https://github.com/sclasen/swfsm/blob/master/fsm/interceptors.go#L53

**Comment by ryanwalls** [comment]
@sclasen Yep, like the idea of composable interceptors.  Will work on implementation after Wed (have a Docker meetup presentation to prepare for).
