### ISSUE TITLE
Factor out Kinesis specific bits

### ISSUE THREAD

**Issue by dgouldin** [sclasen/swfsm#2]
Rather than prescribing how FSM creators will want to handle serialization and storage of decisions, provide generic hooks to allow them to specify their own behavior. Then potentially supply an implementation which mirrors the current Kinesis behavior.

**Comment by sclasen** [comment]
closed by https://github.com/sclasen/swfsm/commit/7ca36ea7b48b4d2c3334e14312a7bdf6d8a66957
