### ISSUE TITLE
Is this in production?

### ISSUE THREAD

**Issue by grantr** [sclasen/swfsm#22]
Interesting work so far!

**Comment by sclasen** [comment]
@grantr Yep, we are using it in production and plan to continue, we will generally be pulling in the best ideas and patterns that emerge from our use, as we did with the ComposableDecider and its related pieces.

**Comment by grantr** [comment]
Good to hear. How has SWF been working for you so far? Would you choose it again?

**Comment by sclasen** [comment]
So far so good. The service itself does have a pretty big surface area so
it takes a bit to get it all in your head, but generally works as
documented.

The aws console for swf is terrible though :)

**Comment by grantr** [comment]
> it takes a bit to get it all in your head

Definitely. I think this is keeping usage (surprisingly) low.

**Comment by sclasen** [comment]
:+1:
