### ISSUE TITLE
Update protobuf to new import path

### ISSUE THREAD

**Issue by uberbrodt** [sclasen/swfsm#52]
http://code.google.com is shut(ting) down, and the golang protobuf project is now here: `https://github.com/golang/protobuf`. I've updated the source files locally and it seems to work. I haven't gotten godep to work with your project yet, otherwise I'd submit a pull request.

**Comment by sclasen** [comment]
Thanks for the reminder @uberbrodt we also need to move off the go-uuid dependency on code.google too.   Go dependency management is so fun! :/

**Comment by uberbrodt** [comment]
Yeah, it's a real blast. Finally got my project dependencies straightened out properly with Godep last week.

**Comment by sclasen** [comment]
@uberbrodt looks like #60 closes this!
