### ISSUE TITLE
Controlling swf logging from calling code

### ISSUE THREAD

**Issue by uberbrodt** [sclasen/swfsm#68]
I'm not sure if there's a solution for this, but I'd like to be able to control the logging output and ideally have some different logging levels for the swfsm library. I use [Logrus](https://github.com/Sirupsen/logrus) for my code. Perhaps if there were a hook that I could inject my own io.Writer via log.New() and redirect, set my own tags, etc?

**Comment by sclasen** [comment]
seems reasonable!  let me look at that

**Comment by sclasen** [comment]
fixed
