### ISSUE TITLE
add a Finish() callback to CoordinatedActivityHandler 

### ISSUE THREAD

**Issue by sclasen** [sclasen/swfsm#75]
this allows cleanup to occur after a task finsihes or fails /cc @dpiddy

**Comment by ryanwalls** [comment]
Maybe #121 is a duplicate of this?

**Comment by sclasen** [comment]
This is different I think. its roughly the equivalent of Cancel() but gets called after task success or failure.

**Comment by dpiddy** [comment]
Closed by #154
